---
title: Python Programming Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  thoughts:
    title: Archives
    output: true
name: Python Programming Blog
description: Wide range of Python tutorials
avatar: https://pythonprogramming.org/images/python.svg
footer-links:
  dribbble:
  email: pythonprogrammingorg@gmail.com
  facebook: "loyalseo"
  flickr:
  github: singh1114
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
disqus: ranvir-singh
google_analytics:
url: https://pythonprogramming.org
baseurl: ""
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-redirect-from
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-cayman
paginate: 10
paginate_path: "/posts/page:num/"
include:
- _categories
- _authors
- _thoughts
series_array: []
