---
title: Best Blog Theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  authors:
    title: Posts
    output: true
name: Best Blog Theme
description: Best Blog Theme
avatar: https://pythonprogramming.org/images/python.svg
footer-links:
  dribbble:
  email: pythonprogrammingorg@gmail.com
  facebook: "loyalseo"
  flickr:
  github: pythonprogramm9
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: pythonprogramm9
  stackoverflow:
  youtube:
disqus: ranvir-singh
google_analytics: UA-73349527-12
url: https://ranvir.xyz
baseurl: "/best"
permalink: "/:title/"
version: v1.2.0
sidebar: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-redirect-from
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-cayman
paginate: 10
paginate_path: "/posts/page:num/"
include:
- _categories
- _authors
show_authors: true
telegram_bot: pythonprogrammingorgbot
