backend:
  name: github
  repo: singh1114/blog
  branch: gh-pages

media_folder: "images"

collections:
  - name: "posts"
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Updated Date", name: "updated_date", widget: "datetime", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Published", name: "published", widget: boolean, default: true}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Canonical URL", name: "canonical_url", widget: "string", required: false}
      - {label: "Skip Table of content", name: "skip_toc", widget: boolean, required: false}
      - {label: "Include math equations", name: "include_mathjax", widget: boolean, required: false}
      - {label: "Redirect From List", name: "redirect_from", widget: "list", required: false, field: {label: "redirect from", widget: "string"}}
      - {label: "Redirect To", name: "redirect_to", widget: "string", required: false}